name: FEniCSx-Shells CI
on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 0 * * 1'
  
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.5.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Flake8 checks
        run: |
          python3 -m flake8 fenicsx_shells
          cd demo && python3 -m flake8 . && cd ../
          python3 -m flake8 test
      - name: isort checks (non-blocking)
        continue-on-error: true
        run: |
          python3 -m isort --check fenicsx_shells
          python3 -m isort --check demo
          python3 -m isort --check test
      
      - name: Install FEniCSx-Shells
        run: |
          python3 -m pip install .

      - name: Build documentation
        run: |
          cd doc
          make html

      - name: Run demos
        run: |
          python3 -m pytest demo
      
      - name: Upload Python documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: |
            doc/build/html/
          retention-days: 2
          if-no-files-found: error

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './doc/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
