name: FEniCSx-Shells CI
on:
  push:
    branches: [ main ]

    schedule:
      - cron: '0 0 * * 1'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.5.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install FEniCSx-Shells
        run: |
          python3 -m pip install .
      - name: Run demos
        run: |
          python3 -m pytest demo
