name: FEniCS-Shellsx CI
on:
  push:
    branches: [ main ]

    schedule:
      - cron: '0 0 * * 1'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: dolfinx/lab
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install FEniCS-Shellsx
        run: |
          python3 -m pip install .
      - name: Convert demo notebooks to scripts
        run: |
          cd demo/documented
          jupyter-nbconvert --to python */*.ipynb
      - name: Run demos
        run: |
          cd demo/documented
          python3 -m pytest .
